linters:
  disable-all: true

  # https://golangci-lint.run/usage/linters
  enable:
    # enabled-by-default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # disabled-by-default
    - gofmt
    - gosec
    - bodyclose
    - gocritic
    - unconvert
    - unparam
    - misspell
    - gocyclo
    - lll
    - goimports
    - revive
    - whitespace
    - errorlint
    - varnamelen
    - wrapcheck
    - depguard
    - dogsled
    - dupl
    - exportloopref
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoinits
    - goconst
    - godot
    - gofumpt
    - goprintffuncname
    - ifshort
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - stylecheck
    - typecheck

run:
  timeout: 5m

linters-settings:
  misspell:
    mode: restricted
  wrapcheck:
    # See https://github.com/tomarrell/wrapcheck#configuration for more information.
    ignoreSigs:
    - .Errorf(
    - errors.New(
    - errors.Unwrap(
    - errors.Join(
    - .Wrap(
    - .Wrapf(
    - .WithMessage(
    - .WithMessagef(
    - .WithStack(
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
  forbidigo:
    forbid:
      - fmt.Print.* # usually just used for debugging purpose
  gocyclo:
    min-complexity: 16
  lll:
    line-length: 200
  varnamelen:
    ignore-names:
      - err
    ignore-decls:
      - t testing.T

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _(test|mock)\.go
      linters:
        - lll
        - errcheck
        - gosec
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
