services:
  node01: &kollekt-api
    stdin_open: true
    tty: true
    image: waldirborbajr/kollekt:dev
    # container_name: kollekt_node01
    hostname: node01
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"
    networks:
      - kollekt_network

  node02:
    <<: *kollekt-api
    hostname: node02
    environment:
      - PORT=3002
    ports:
      - "3002:3002"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node01
      - node02
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"
    networks:
      - kollekt_network

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=kollekt
      - POSTGRES_USER=admin
      - POSTGRES_DB=kollektdb
    expose:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.56'
          memory: '400MB'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d kollektdb'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

networks:
  kollekt_network:
    # driver: bridge
    # external: true
    # attachable: true

# volumes:
#   kollekt_data:
#     external: true
