services:
  kollekt:
    stdin_open: true
    tty: true
    image: waldirborbajr/kollekt:dev
    container_name: kollekt
    hostname: kollekt
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    # networks:
    #   - kollekt_network

  # api-python:
  #   build:
  #     context: ./remote/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - kollektnet

# networks:
#   kollekt_network:
#     # driver: bridge
#     external: true
#     attachable: true
#
# volumes:
#   kollekt_data:
#     external: true
